# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6d96f85ee542a74247d3b7a60b86a3e38e1294f45c89e2524fb5ba76fc16b41bc75589f10c434d58654076084ae09eacfba99414cb343d8c60390d05c5d9bc02

test:
  secret_key_base: 8c517d985eded6e8c0bcaa2733438edd7d80017b21c9fb2c877c956c31aa7b589ca0340f25fa0e0dd9b44c94fbcfa0ab14dab6db72bb627ebf1397c890bd18bb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
